# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "sab-centos/7"
  config.vm.network "private_network", ip: "192.168.50.5"

  # do not auto-update guest tools
  #config.vbguest.auto_update = false

  # config
  config.vm.provider "virtualbox" do |vb|
    vb.name = "010-ansible-web-app-manual"
  end

  # configure the VM
  config.vm.provision "shell", inline: <<-SHELL
    echo '***System update...'
    ulimit -n 4048
    yum clean all
    yum update -y

    echo '***IPTables config / rules...'
    service NetworkManager stop >/dev/null 2>&1
    chkconfig NetworkManager off >/dev/null 2>&1
    yum install -y iptables-services
    systemctl stop firewalld && sudo systemctl start iptables; sudo systemctl start ip6tables
    systemctl disable firewalld
    systemctl mask firewalld
    systemctl enable iptables
    systemctl start iptables
    iptables -I INPUT 1 -p tcp -m state --state new -m tcp --dport 5000 -j ACCEPT
    service iptables save

    echo '***Setup for runtime'
    yum install -y python3 python3-pip mariadb-server
    systemctl start mariadb
    pip3 install --user flask
    pip3 install --user flask-mysql
  SHELL
end

